export const ATHLETE_LIST_REQUEST = 'ATHLETE_LIST_REQUEST'
export const ATHLETE_LIST_SUCCESS = 'ATHLETE_LIST_SUCCESS'
export const ATHLETE_LIST_FAIL = 'ATHLETE_LIST_FAIL'

export const ADD_ATHLETE = 'ADD_ATHLETE'
export const REMOVE_ATHLETE = 'REMOVE_ATHLETE'

export const RANDOM_TEAM = 'RANDOM_TEAM'
export const OPPONENT_TEAM = 'OPPONENT_TEAM'
export const GET_TEAM = 'GET_TEAM'
export const EMPTY_TEAM = 'EMPTY_TEAM'
export const GET_TEAM_COST = 'GET_TEAM_COST'

export const SHOW_LINEUP = 'SHOW_LINEUP'
export const SHOW_ATHLETE_LIST = 'SHOW_ATHLETE_LIST'
export const SHOW_CALENDAR = 'SHOW_CALENDAR'
