const events = [
  {
    _id: '1',
    sports_name: 'soccer',
    icon: '/images/icons/sport/soccer.png',
    start_at: '2021-04-12 18:30:00',
    date: '12/04 Lun',
    time: '18.30',
    league: 'Liga',
    first_team: {
      full_name: 'Barcellona',
      short_name: 'FCB',
      color_1: '#A50044',
      color_2: '#004D98',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
    },
    second_team: {
      full_name: 'Real Madrid',
      short_name: 'RMA',
      color_1: '#FFFFFF',
      color_2: '#A68D52',
      color_3: '#B2995F',
      color_4: '#FFFFFF',
    },
    name: null,
  },
  {
    _id: '2',
    sports_name: 'soccer',
    icon: '/images/icons/sport/soccer.png',
    start_at: '2021-04-12 19:30:00',
    date: '12/04 Lun',
    time: '19.30',
    league: 'Bundesliga',
    first_team: {
      full_name: 'Bayern Munich',
      short_name: 'MUN',
      color_1: '#D53E43',
      color_2: '#FFFFFF',
      color_3: '#FFFFFF',
      color_4: '#D53E43',
    },

    second_team: {
      full_name: 'Borussia Dortmund',
      short_name: 'BVB',
      color_1: '#FADA4A',
      color_2: '#000000',
      color_3: '#000000',
      color_4: '#FADA4A',
    },
    name: null,
  },
  {
    _id: '3',
    sports_name: 'basket',
    icon: '/images/icons/sport/basket.png',
    start_at: '2021-04-13 00:25:00',
    date: '13/04 Mar',
    time: '00.30',
    league: 'NBA',
    first_team: {
      full_name: 'Brooklyn Nets',
      short_name: 'Nets',
      color_1: '#000000',
      color_2: '#FFFFFF',
      color_3: '#FFFFFF',
      color_4: '#000000',
    },
    second_team: {
      full_name: 'Dallas Mavericks',
      short_name: 'Mavs',
      color_1: '#00538C',
      color_2: '#002B5E',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
    },
    name: null,
  },
  {
    _id: '4',
    sports_name: 'tennis',
    icon: '/images/icons/sport/tennis.png',
    start_at: '2021-04-12 20:20:00',
    date: '12/04 Lun',
    time: '20.30',
    league: 'Wimbledon',
    first_team: {
      full_name: 'Denis Shapovalov',
      short_name: 'Shapovalov',
      color_1: '#FF0000',
      color_2: '#FFFFFF',
      color_3: '#FFFFFF',
      color_4: '#FF0000',
    },
    second_team: {
      full_name: 'Alex De Minaur',
      short_name: 'De Minaur',
      color_1: '#F1D934',
      color_2: '#198E95',
      color_3: '#198E95',
      color_4: '#F1D934',
    },
    name: null,
  },
  {
    _id: '5',
    sports_name: 'basket',
    icon: '/images/icons/sport/basket.png',
    start_at: '2021-04-13 02:30:00',
    date: '13/04 Mar',
    time: '02.30',
    league: 'NBA',
    first_team: {
      full_name: 'Golden State Warriors',
      short_name: 'Warriors',
      color_1: '#1D428A',
      color_2: '#FFC72C',
      color_3: '#FFC72C',
      color_4: '#1D428A',
    },
    second_team: {
      full_name: 'Los Angeles Lakers',
      short_name: 'Lakers',
      color_1: '#552583',
      color_2: '#FDB927',
      color_3: '#FDB927',
      color_4: '#552583',
    },
    name: null,
  },
  {
    _id: '6',
    sports_name: 'f1',
    icon: '/images/icons/sport/f1.png',
    start_at: '2021-04-13 11:30:00',
    date: '13/04 Mar',
    time: '11.30',
    league: 'Formula Uno',
    first_team: null,
    second_team: null,
    name: 'GP Monza',
  },
  {
    _id: '7',
    sports_name: 'motogp',
    icon: '/images/icons/sport/motogp.png',
    start_at: '2021-04-12 20:30:00',
    date: '12/04 Lun',
    time: '20.30',
    league: 'Moto Gp',
    first_team: null,
    second_team: null,
    name: 'GP USA',
  },
  {
    _id: '8',
    sports_name: 'football',
    icon: '/images/icons/sport/football.png',
    start_at: '2021-04-13 00:15:00',
    date: '13/04 Mar',
    time: '00.15',
    league: 'NFL',
    first_team: {
      full_name: 'Green Bay Packers',
      short_name: 'Packers',
      color_1: '#203731',
      color_2: '#FFB612',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
    },
    second_team: {
      full_name: 'Houston Texans',
      short_name: 'Texans',
      color_1: '#03202F',
      color_2: '#A71930',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
    },
    name: null,
  },
  {
    _id: '9',
    sports_name: 'soccer',
    icon: '/images/icons/sport/soccer.png',
    start_at: '2021-04-13 12:30:00',
    date: '13/04 Mar',
    time: '12.30',
    league: 'Serie A',
    first_team: {
      full_name: 'Inter',
      short_name: 'INT',
      color_1: '#0068A8',
      color_2: '#221F20',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
    },
    second_team: {
      full_name: 'AC Milan',
      short_name: 'MIL',
      color_1: '#FB090B',
      color_2: '#000000',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
    },
    name: null,
  },
  {
    _id: '10',
    sports_name: 'tennis',
    icon: '/images/icons/sport/tennis.png',
    start_at: '2021-04-12 23:30:00',
    date: '12/04 Lun',
    time: '23.30',
    league: 'Wimbledon',
    first_team: {
      full_name: 'Jannik Sinner',
      short_name: 'Sinner',
      color_1: '#3C95F7',
      color_2: '#FFFFFF',
      color_3: '#FFFFFF',
      color_4: '#3C95F7',
    },
    second_team: {
      full_name: 'Gael Monfils',
      short_name: 'Monfils',
      color_1: '#0055A4',
      color_2: '#EF4135',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
    },
    name: null,
  },
  {
    _id: '11',
    sports_name: 'soccer',
    icon: '/images/icons/sport/soccer.png',
    start_at: '2021-04-12 20:30:00',
    date: '12/04 Lun',
    time: '20.30',
    league: 'Serie A',
    first_team: {
      full_name: 'Juventus',
      short_name: 'JUV',
      color_1: '#000000',
      color_2: '#FFFFFF',
      color_3: '#FFFFFF',
      color_4: '#000000',
    },
    second_team: {
      full_name: 'Roma',
      short_name: 'ASR',
      color_1: '#8E1F2F',
      color_2: '#F0BC42',
      color_3: '#F0BC42',
      color_4: '#8E1F2F',
    },
    name: null,
  },
  {
    _id: '12',
    sports_name: 'soccer',
    icon: '/images/icons/sport/soccer.png',
    start_at: '2021-04-12 15:30:00',
    date: '12/04 Lun',
    time: '15.30',
    league: 'Premier League',
    first_team: {
      full_name: 'Liverpool',
      short_name: 'LIV',
      color_1: '#C8102E',
      color_2: '#FFFFFF',
      color_3: '#FFFFFF',
      color_4: '#C8102E',
    },
    second_team: {
      full_name: 'Manchester City',
      short_name: 'Man City',
      color_1: '#6CABDD',
      color_2: '#66468B',
      color_3: '#66468B',
      color_4: '#6CABDD',
    },
    name: null,
  },
  {
    _id: '13',
    sports_name: 'basket',
    icon: '/images/icons/sport/basket.png',
    start_at: '2021-04-13 01:30:00',
    date: '13/04 Mar',
    time: '01.30',
    league: 'NBA',
    first_team: {
      full_name: 'Milwaukee Bucks',
      short_name: 'Bucks',
      color_1: '#00471B',
      color_2: '#EEE1C6',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
    },
    second_team: {
      full_name: 'Los Angeles Clippers',
      short_name: 'Clippers',
      color_1: '#C8102E',
      color_2: '#1D428A',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
    },
    name: null,
  },
  {
    _id: '14',
    sports_name: 'tennis',
    icon: '/images/icons/sport/tennis.png',
    start_at: '2021-04-12 21:45:00',
    date: '12/04 Lun',
    time: '21.45',
    league: 'Wimbledon',
    first_team: {
      full_name: 'Novak Djokovic',
      short_name: 'Djokovic',
      color_1: '#0C4076',
      color_2: '#C6363C',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
    },
    second_team: {
      full_name: 'Alexander Zverev',
      short_name: 'Zverev',
      color_1: '#FFFFFF',
      color_2: '#000000',
      color_3: '#000000',
      color_4: '#FFFFFF',
    },
    name: null,
  },
  {
    _id: '15',
    sports_name: 'tennis',
    icon: '/images/icons/sport/tennis.png',
    start_at: '2021-04-12 20:25:00',
    date: '12/04 Lun',
    time: '20.25',
    league: 'Wimbledon',
    first_team: {
      full_name: 'Roger Federer',
      short_name: 'Federer',
      color_1: '#D52B1E',
      color_2: '#FFFFFF',
      color_3: '#FFFFFF',
      color_4: '#D52B1E',
    },
    second_team: {
      full_name: 'Rafa Nadal',
      short_name: 'Nadal',
      color_1: '#AA151B',
      color_2: '#F1BF00',
      color_3: '#F1BF00',
      color_4: '#AA151B',
    },
    name: null,
  },
  {
    _id: '16',
    sports_name: 'tennis',
    icon: '/images/icons/sport/tennis.png',
    start_at: '2021-04-13 13:05:00',
    date: '13/04 Lun',
    time: '13.05',
    league: 'Wimbledon',
    first_team: {
      full_name: 'Stan Wawrinka',
      short_name: 'Wawrinka',
      color_1: '#D52B1E',
      color_2: '#FFFFFF',
      color_3: '#FFFFFF',
      color_4: '#D52B1E',
    },
    second_team: {
      full_name: 'Dominic Thiem',
      short_name: 'Thiem',
      color_1: '#ED2939',
      color_2: '#FFFFFF',
      color_3: '#FFFFFF',
      color_4: '#ED2939',
    },
    name: null,
  },
  {
    _id: '17',
    sports_name: 'football',
    icon: '/images/icons/sport/football.png',
    start_at: '2021-04-13 01:45:00',
    date: '13/04 Mar',
    time: '01.45',
    league: 'NFL',
    first_team: {
      full_name: 'Tampa Bay Buccaneers',
      short_name: 'Bucs',
      color_1: '#D50A0A',
      color_2: '#FF7900',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
    },
    second_team: {
      full_name: 'Los Angeles Rams',
      short_name: 'Rams',
      color_1: '#002244',
      color_2: '#866D4B',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
    },
    name: null,
  },
]

export default events
