const athlete = {
  _id: '3',
  sport_name: 'soccer',
  name: {
    first_name: 'Lionel',
    last_name: 'Messi',
    short_name: 'L. Messi',
    uniform_name: 'Messi',
  },
  country: { name: null, short_name: null },
  pos: 'A',
  num: '10',
  next_event: {
    league_name: 'Liga',
    team: {
      full_name: 'Barcellona',
      short_name: 'FCB',
      jersey: '/images/jersey/38.png',
      color_1: '#A50044',
      color_2: '#004D98',
      color_3: '#FFFFFF',
      color_4: '#FFFFFF',
      color_jrs: '#fac72e',
      color_jrsGk: '#023474',
      color_sqr: '#2a3a78',
    },
    opponent: {
      full_name: 'Real Madrid',
      short_name: 'RMA',
      color_1: '#FFFFFF',
      color_2: '#A68D52',
      color_3: '#B2995F',
      color_4: '#FFFFFF',
    },
    name: 'Barcellona - Real Madrid',
    start_at: 'April 13, 2021 20:45:00',
    cost: 6.97,
  },
  fppg: 5.334,
  past_events: [
    {
      event_info: {
        event_date: '25/10',
        event_name: null,
        opponent: {
          full_name: 'Real Madrid',
          short_name: 'RMA',
          color_1: '#FFFFFF',
          color_2: '#A68D52',
          color_3: '#B2995F',
          color_4: '#FFFFFF',
        },
        rating: 11.54,
        cost: 10,
      },
      event_data: {
        fanta: {
          has_gk: 0,
          has_def: 0,
          goal: 4.8,
          assist: 0.8,
          yellowCards: 0.0,
          redCards: 0.0,
          ownGoal: 0.0,
          teamWon: 0.4,
          goals_conceded: -0.12,
          goals_own_team: 2.4,
          clean_sheet: 0.0,
          pen_save: 0.0,
          pen_committed: 0.0,
          pen_won: 0.0,
          pen_miss: 0.0,
          shots_total: 0.24,
          shots_on_goal: 0.48,
          correct_passes: 1.58,
          missed_passes: -0.11,
          keyPasses: 0.8,
          acc_crosses: 0.0,
          missed_crosses: 0.0,
          dribbleSucc: 1.05,
          def_int: 0.4,
          hit_woodwork: 0.0,
          saves: 0.0,
          savesInsideBox: 0.0,
          fouls_drawn: 0.04,
          fouls_commited: -0.04,
        },
        stats: {
          has_gk: 0,
          has_def: 0,
          goal: 2,
          assist: 1,
          yellowCards: 0,
          redCards: 0,
          ownGoal: 0,
          teamWon: 1,
          goals_conceded: 1,
          goals_own_team: 6,
          clean_sheet: 0,
          pen_save: 0,
          pen_committed: 0,
          pen_won: 0,
          pen_miss: 0,
          shots_total: 3,
          shots_on_goal: 3,
          correct_passes: 63,
          missed_passes: 9,
          keyPasses: 2,
          acc_crosses: 0,
          missed_crosses: 0,
          dribbleSucc: 3,
          def_int: 1,
          hit_woodwork: 0,
          saves: 0,
          savesInsideBox: 0,
          fouls_drawn: 1,
          fouls_commited: 1,
        },
      },
    },
  ],
}
